In [66]:

import pandas as pd

import numpy as np

In [67]:
data = pd.read_csv('prix_vente.csv',",")
data

,nom_commune,prix_appartement_bas_m2_vente,prix_appartement_haut_m2_vente,prix_appartement_moyen_m2_vente,prix_maison_bas_m2_vente,prix_maison_haut_m2_vente,prix_maison_moyen_m2_vente
0,Montreuil,5250.0,7793.34,5372.75,4606.59,7725.02,4736.1
1,Montreuil,3495.34,4390.24,3454.25,4528.57,7775.16,4703.25
2,Montreuil,1933.12,2598.89,1917.33,2133.33,3228.33,2172.27
3,Montreuil,4500.0,7500.0,4763.37,4500.0,7500.0,4763.37
4,Montreuil,4264.71,7493.28,4624.96,4264.71,7493.28,4624.96
5,Montreuil,1854.29,7150.75,3048.34,1854.29,7150.75,3048.34
6,Montreuil,1842.11,7140.81,3028.93,1842.11,7140.81,3028.93
7,Montreuil,5195.95,7676.67,5276.53,5195.95,7676.67,5276.53
8,Montreuil,1809.09,7083.33,3010.99,1809.09,7083.33,3010.99
9,Montreuil,1777.74,7083.33,2982.58,1777.74,7083.33,2982.58
10,Montreuil,1740.84,7036.36,2927.1,1740.84,7036.36,2927.1
11,Montreuil,1741.67,7013.23,2926.05,1741.67,7013.23,2926.05
12,Montreuil,1787.37,7083.33,2995.35,1787.37,7083.33,2995.35
13,Montreuil,5223.88,7700.0,5276.12,5223.88,7700.0,5276.12
14,Montreuil,1688.31,6842.11,2836.37,1688.31,6842.11,2836.37
15,Montreuil,1688.31,6842.11,2836.37,1688.31,6842.11,2836.37
16,Paris,12000.0,14718.75,12557.53,3850.93,3850.93,3850.93
17,Paris,12000.0,15000.0,12638.67,3850.93,3850.93,3850.93
18,Paris,2476.14,3457.86,2430.6,1806.25,2779.32,1896.66
19,Paris,2596.49,4037.16,2816.1,2933.69,3759.21,2933.7
20,Paris,13083.33,19369.37,12418.13,13083.33,19369.37,12418.13
21,Paris,13020.0,19369.37,12306.85,13020.0,19369.37,12306.85
22,Paris,1942.33,16062.92,4754.91,1942.33,16062.92,4754.91
23,Paris,1883.87,14619.79,3958.85,1883.87,14619.79,3958.85
24,Paris,12000.0,14718.75,12557.53,2296.88,2296.88,2296.88
25,Paris,12000.0,15000.0,12638.67,2296.88,2296.88,2296.88
26,Paris,5842.81,8000.0,5801.65,2296.88,2296.88,2296.88
27,Paris,12093.81,15227.27,12006.42,12093.81,15227.27,12006.42
28,Paris,12093.02,15151.03,11974.61,12093.02,15151.03,11974.61
29,Paris,12131.15,15227.27,12364.74,12131.15,15227.27,12364.74
...,...,...,...,...,...,...,...
860,Limoges,1360.0,2415.09,1463.22,1360.0,2415.09,1463.22
861,Limoges,1364.71,2476.89,1471.31,1364.71,2476.89,1471.31
862,Limoges,1369.01,2526.09,1475.74,1369.01,2526.09,1475.74
863,Limoges,1363.01,2466.55,1467.52,1363.01,2466.55,1467.52
864,Limoges,1538.36,3609.41,1816.89,1538.36,3609.41,1816.89
865,Limoges,1554.35,3654.05,1849.46,1554.35,3654.05,1849.46
866,Limoges,1554.35,3654.05,1849.46,1554.35,3654.05,1849.46
867,Nice,2809.52,4278.59,2851.03,5195.24,12095.74,5694.49
868,Nice,4625.0,9000.0,5095.86,4625.0,9000.0,5095.86
869,Nice,5000.0,9258.2,5419.02,5000.0,9258.2,5419.02
870,Nice,5000.0,9258.2,5419.02,5000.0,9258.2,5419.02
871,Nice,5000.0,9257.14,5405.73,5000.0,9257.14,5405.73
872,Nice,4979.17,9252.86,5384.61,4979.17,9252.86,5384.61
873,Nice,5000.0,9166.67,5370.85,5000.0,9166.67,5370.85
874,Nice,5000.0,9162.99,5371.12,5000.0,9162.99,5371.12
875,Nice,5061.74,9079.37,5373.18,5061.74,9079.37,5373.18
876,Nice,4990.0,9057.84,5337.25,4990.0,9057.84,5337.25
877,Nice,5125.0,9062.5,5391.13,5125.0,9062.5,5391.13
878,Nice,5102.56,9240.0,5483.71,5102.56,9240.0,5483.71
879,Nice,5000.0,9308.64,5471.26,5000.0,9308.64,5471.26
880,Nice,5000.0,9308.64,5471.26,5000.0,9308.64,5471.26
881,Lyon,5205.63,7472.22,5371.77,5205.63,7472.22,5371.77
882,Lyon,5784.12,12366.07,6322.23,5784.12,12366.07,6322.23
883,Lyon,4684.21,7535.71,4893.69,4684.21,7535.71,4893.69
884,Lyon,5069.44,6922.44,5233.96,5069.44,6922.44,5233.96
885,Lyon,5173.08,7181.82,4888.26,5173.08,7181.82,4888.26
886,Lyon,6258.06,9158.4,6427.05,6258.06,9158.4,6427.05
887,Lyon,4853.66,6478.21,4820.0,4853.66,6478.21,4820.0
888,Lyon,4021.28,6333.58,4093.07,4021.28,6333.58,4093.07
889,Lyon,3180.85,5186.14,3348.9,3180.85,5186.14,3348.9

In [68]:
len(np.unique(list(data["nom_commune"])))

40

In [72]:
data[data["prix_appartement_moyen_m2_vente"]=="NC"]

Empty DataFrame
Columns: [nom_commune, prix_appartement_bas_m2_vente, prix_appartement_haut_m2_vente, prix_appartement_moyen_m2_vente, prix_maison_bas_m2_vente, prix_maison_haut_m2_vente, prix_maison_moyen_m2_vente]
Index: []